In [25]:
#importing files
import pandas as pd
import numpy as np

In [26]:
#import data
data_df=pd.read_csv('/Users/Atluri/Downloads/powerconsumption.csv.zip')

In [27]:
data_df.head()

Datetime  Temperature  Humidity  WindSpeed  GeneralDiffuseFlows  \
0  1/1/2017 0:00        6.559      73.8      0.083                0.051   
1  1/1/2017 0:10        6.414      74.5      0.083                0.070   
2  1/1/2017 0:20        6.313      74.5      0.080                0.062   
3  1/1/2017 0:30        6.121      75.0      0.083                0.091   
4  1/1/2017 0:40        5.921      75.7      0.081                0.048   

   DiffuseFlows  PowerConsumption_Zone1  PowerConsumption_Zone2  \
0         0.119             34055.69620             16128.87538   
1         0.085             29814.68354             19375.07599   
2         0.100             29128.10127             19006.68693   
3         0.096             28228.86076             18361.09422   
4         0.085             27335.69620             17872.34043   

   PowerConsumption_Zone3  
0             20240.96386  
1             20131.08434  
2             19668.43373  
3             18899.27711  
4             18442.40964

In [28]:
data_df['Datetime'] = pd.to_datetime(data_df['Datetime'])  
data_df['Year'] = data_df['Datetime'].dt.year
data_df['Month'] = data_df['Datetime'].dt.month
data_df['Day'] = data_df['Datetime'].dt.day
data_df['Hour'] = data_df['Datetime'].dt.hour
data_df['Minute'] = data_df['Datetime'].dt.minute
data_df = data_df.drop(['Datetime'], axis=1)

In [29]:
data_df.head()

Temperature  Humidity  WindSpeed  GeneralDiffuseFlows  DiffuseFlows  \
0        6.559      73.8      0.083                0.051         0.119   
1        6.414      74.5      0.083                0.070         0.085   
2        6.313      74.5      0.080                0.062         0.100   
3        6.121      75.0      0.083                0.091         0.096   
4        5.921      75.7      0.081                0.048         0.085   

   PowerConsumption_Zone1  PowerConsumption_Zone2  PowerConsumption_Zone3  \
0             34055.69620             16128.87538             20240.96386   
1             29814.68354             19375.07599             20131.08434   
2             29128.10127             19006.68693             19668.43373   
3             28228.86076             18361.09422             18899.27711   
4             27335.69620             17872.34043             18442.40964   

   Year  Month  Day  Hour  Minute  
0  2017      1    1     0       0  
1  2017      1    1     0      10  
2  2017      1    1     0      20  
3  2017      1    1     0      30  
4  2017      1    1     0      40

In [30]:
x = data_df.drop(['PowerConsumption_Zone1', 'PowerConsumption_Zone2', 'PowerConsumption_Zone3'], axis=1).values
y=data_df[['PowerConsumption_Zone1', 'PowerConsumption_Zone2', 'PowerConsumption_Zone3']].values

In [31]:
print(x)

[[ 6.559 73.8    0.083 ...  1.     0.     0.   ]
 [ 6.414 74.5    0.083 ...  1.     0.    10.   ]
 [ 6.313 74.5    0.08  ...  1.     0.    20.   ]
 ...
 [ 6.9   72.8    0.086 ... 30.    23.    30.   ]
 [ 6.758 73.     0.08  ... 30.    23.    40.   ]
 [ 6.58  74.1    0.081 ... 30.    23.    50.   ]]


In [32]:
print(y)

[[34055.6962  16128.87538 20240.96386]
 [29814.68354 19375.07599 20131.08434]
 [29128.10127 19006.68693 19668.43373]
 ...
 [29590.87452 25277.69254 13806.48259]
 [28958.1749  24692.23688 13512.60504]
 [28349.80989 24055.23167 13345.4982 ]]


In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=0)

In [57]:
# LASSO

In [34]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha=0.001)
lasso.fit(x_train, y_train)
y_pred1 = lasso.predict(x_test)

In [58]:
# ELASTICNET

In [35]:
from sklearn.linear_model import ElasticNet
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
x_scaled = s.fit_transform(x)
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5) 
elastic_net.fit(x_train, y_train)
y_pred2 = elastic_net.predict(x_test)

In [60]:
# ENSEMBLES
# BAGGING

In [36]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=100, random_state=0)
rf.fit(x_train, y_train)
y_pred3 = rf.predict(x_test)

In [59]:
# BOOSTING

In [37]:
import xgboost as xgb
from xgboost import XGBRegressor
model = XGBRegressor(n_estimators=1000, max_depth=6, learning_rate=0.1, objective='reg:squarederror', random_state=0)
model.fit(x_train, y_train)
y_pred4 = model.predict(x_test)

In [38]:
print(y_pred1)
print(y_pred2)
print(y_pred3)
print(y_pred4)

[[27439.3907273  16496.69761564 18205.62810928]
 [25395.42826778 17750.99864206 14709.64791419]
 [35199.82680064 23719.61329361 19636.55903689]
 ...
 [26073.03012643 15289.0299528  16042.99277043]
 [30718.45728921 18481.81999792 17317.11967031]
 [32019.16036867 18704.81140189 18075.68992361]]
[[27437.56018316 16502.61286481 18188.9077005 ]
 [25406.27251595 17751.2503714  14717.68847234]
 [35204.70646224 23717.51242759 19641.12901681]
 ...
 [26070.73392669 15296.21740475 16032.77976537]
 [30725.02266028 18490.01360957 17310.21757483]
 [32013.58449939 18710.48352409 18063.25020974]]
[[28006.9509924 17455.9958422 21349.3956918]
 [26330.258206  17503.9170119 13106.9471127]
 [27567.6530946 15564.1621622 13905.369562 ]
 ...
 [25249.8255752 14771.4427249 15571.9384643]
 [32984.6146188 20346.5882574 15968.5603141]
 [34658.0451814 22438.0191641 17490.8088617]]
[[30439.2   18380.01  23079.16 ]
 [26771.092 17619.154 13316.007]
 [27396.006 15661.502 14305.179]
 ...
 [25235.666 14601.615 15542.04 ]

In [39]:
las=lasso.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
en=elastic_net.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
rf=rf.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
m=model.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
print(las)
print(en)
print(rf)
print(m)

[[20328.06389336 11325.3316984  10938.38384596]]
[[20340.00257422 11339.53751219 10939.09094258]]
[[31826.5954077 17140.1580548 19514.1455162]]
[[32719.11  17533.035 20102.418]]


In [40]:
from sklearn.metrics import r2_score
r2_lasso=r2_score(y_test,y_pred1)
print(r2_lasso)
r2_elasticnet=r2_score(y_test, y_pred2)
print(r2_elasticnet)
r2_randomforest = r2_score(y_test, y_pred3)
print(r2_randomforest)
r2_xgb=r2_score(y_test,y_pred4)
print(r2_xgb)

0.6031045998549744
0.6031121710068916
0.9846753768375645
0.9872344612567713


In [49]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lasso, x_train, y_train, scoring='r2', cv=5)
print( scores.mean())
# crossvalidation

0.6097771199160563


In [61]:
# using light gbm for faster and efficient calculation
# BUT ONLY 1 OUTPUT

In [52]:
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
train_data = lgb.Dataset(x_train_scaled, label=y_train[:, 0])  #predicting PowerConsumption_Zone1
test_data = lgb.Dataset(x_test_scaled, label=y_test[:, 0], reference=train_data)
params = {'objective': 'regression','metric': 'rmse','boosting_type': 'gbdt','num_leaves': 31,'learning_rate': 0.05,'feature_fraction': 0.9}
num_round = 1000
lgbm = lgb.train(params, train_data, num_round, valid_sets=[test_data])
# used light gbm as its faster and more efficient 

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001987 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1343
[LightGBM] [Info] Number of data points in the train set: 31449, number of used features: 9
[LightGBM] [Info] Start training from score 32353.483477


In [53]:
y_pred5 = lgbm.predict(x_test_scaled, num_iteration=model.best_iteration)
r2 = r2_score(y_test[:, 0], y_pred5)
print(r2)

0.9812326838488566


In [54]:
lgbm.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
# ZONE1

array([37540.25918473])

In [65]:
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
train_data = lgb.Dataset(x_train_scaled, label=y_train[:, 1])  #predicting PowerConsumption_Zone2
test_data = lgb.Dataset(x_test_scaled, label=y_test[:, 1], reference=train_data)
params = {'objective': 'regression','metric': 'rmse','boosting_type': 'gbdt','num_leaves': 31,'learning_rate': 0.05,'feature_fraction': 0.9}
num_round = 1000
lgbm = lgb.train(params, train_data, num_round, valid_sets=[test_data])
# used light gbm as its faster and more efficient 

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002077 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1343
[LightGBM] [Info] Number of data points in the train set: 31449, number of used features: 9
[LightGBM] [Info] Start training from score 21053.109094


In [67]:
y_pred51 = lgbm.predict(x_test_scaled, num_iteration=model.best_iteration)
r2 = r2_score(y_test[:, 1], y_pred51)
print(r2)

0.9778591428478717


In [68]:
lgbm.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
# ZONE2

array([24078.21326055])

In [70]:
import lightgbm as lgb
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
train_data = lgb.Dataset(x_train_scaled, label=y_train[:, 2])  #predicting PowerConsumption_Zone2
test_data = lgb.Dataset(x_test_scaled, label=y_test[:, 2], reference=train_data)
params = {'objective': 'regression','metric': 'rmse','boosting_type': 'gbdt','num_leaves': 31,'learning_rate': 0.05,'feature_fraction': 0.9}
num_round = 1000
lgbm = lgb.train(params, train_data, num_round, valid_sets=[test_data])
# used light gbm as its faster and more efficient 

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002170 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1343
[LightGBM] [Info] Number of data points in the train set: 31449, number of used features: 9
[LightGBM] [Info] Start training from score 17841.136461


In [71]:
y_pred51 = lgbm.predict(x_test_scaled, num_iteration=model.best_iteration)
r2 = r2_score(y_test[:, 2], y_pred51)
print(r2)

0.9925209481879327


In [76]:
lgbm.predict([[6.559,	73.8,	0.083,	0.051,	0.119,2017,1,1,0, 0]])
# ZONE3

array([14454.84620777])

In [77]:
# used lasso regression initially as it is said to deal efficiently with hidh dimensional data
# but it didnt give good r2 value tried to standardize it but it didnt acheive any increase in the r2 value also triend feature removal also
# but it didnt fetch good results
# then tried to use elastic net which is combination of lasso and ridge regression i guess was a bad choice as ridge regression involved as
# ridge regression is used when there are more predictor variables than observations
# then i started using random forest regressor from the ensemble because it involves bagging through which data is split and many algorithms are 
# used to make predictions and it combines all of these to attain the final result 
# it worked well with around 0.98.. r2 value(changed random state from 42 to 0 to get the same values every time)
# then i shifted towards using ensemble learning
# so i used boosting technique where a sequence of models each model checks and corrects the error of the previous model
# so i used xgboost which gave r2 of 0.98
# tried to increase the r2 values of lasso and elastic net because ensembles took a considerable amount of time to process  
# but it was not progressive
# so again tried to do things using ensemble methods
# found lightgbm which took considerably less time

# still not done with learning lightgbm

In [78]:
# learnings
# regression models are more efficient with less number of datapoints
# linear regression model is only useful when there is a variable and we predict another majority time its useless when involving many dimensions
# ensemble techniques are useful when large data is involved

In [79]:
# to do
# lightgbm multioutput way